name: Conviso AST & Security Gate

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisoast:latest
    env:
      CONVISO_API_KEY: ${{ secrets.CONVISO_API_KEY }}

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar arquivo de regras do Security Gate
        run: |
          cat <<EOF > security-gate.yml
          rules:
            - from: any
              severity: critical
              maximum: 0
            - from: any
              severity: high
              maximum: 0
          EOF

      - name: Executar Conviso AST Scan
        run: conviso ast run

      - name: Executar Security Gate
        run: conviso vulnerability assert-security-rules --rules-file 'security-gate.yml'
