name: Conviso Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisoast:latest
    env:
      CONVISO_API_KEY: ${{ secrets.CONVISO_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Conviso AST Scan
        run: conviso ast run

      - name: Run Security Gate
        run: conviso security-gate run
